// <auto-generated />
using Laboratorio.CRUD.Company.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Laboratorio.CRUD.Company.Infra.Data.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    partial class SqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Laboratorio.CRUD.Company.Domain.Entities.CompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SizeId");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Empresa 01",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Empresa 02",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Empresa 03",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Empresa 04",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Empresa 05",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Empresa 06",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Empresa 07",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Empresa 08",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Empresa 09",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Empresa 10",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Empresa 11",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Empresa 12",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Empresa 13",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Empresa 14",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Empresa 15",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Empresa 16",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Empresa 17",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "Empresa 18",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "Empresa 19",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 20,
                            Name = "Empresa 20",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "Empresa 21",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "Empresa 22",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "Empresa 23",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 24,
                            Name = "Empresa 24",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 25,
                            Name = "Empresa 25",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 26,
                            Name = "Empresa 26",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 27,
                            Name = "Empresa 27",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 28,
                            Name = "Empresa 28",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 29,
                            Name = "Empresa 29",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 30,
                            Name = "Empresa 30",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 31,
                            Name = "Empresa 31",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 32,
                            Name = "Empresa 32",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 33,
                            Name = "Empresa 33",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 34,
                            Name = "Empresa 34",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 35,
                            Name = "Empresa 35",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 36,
                            Name = "Empresa 36",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 37,
                            Name = "Empresa 37",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 38,
                            Name = "Empresa 38",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 39,
                            Name = "Empresa 39",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 40,
                            Name = "Empresa 40",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 41,
                            Name = "Empresa 41",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 42,
                            Name = "Empresa 42",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 43,
                            Name = "Empresa 43",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 44,
                            Name = "Empresa 44",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 45,
                            Name = "Empresa 45",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 46,
                            Name = "Empresa 46",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 47,
                            Name = "Empresa 47",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 48,
                            Name = "Empresa 48",
                            SizeId = 2
                        },
                        new
                        {
                            Id = 49,
                            Name = "Empresa 49",
                            SizeId = 1
                        },
                        new
                        {
                            Id = 50,
                            Name = "Empresa 50",
                            SizeId = 1
                        });
                });

            modelBuilder.Entity("Laboratorio.CRUD.Company.Domain.Entities.CompanySizeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.ToTable("SizeCompany", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pequena"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Média"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Grande"
                        });
                });

            modelBuilder.Entity("Laboratorio.CRUD.Company.Domain.Entities.CompanyEntity", b =>
                {
                    b.HasOne("Laboratorio.CRUD.Company.Domain.Entities.CompanySizeEntity", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Size");
                });
#pragma warning restore 612, 618
        }
    }
}
